package modelo;
// Generated 14/08/2015 20:26:10 by Hibernate Tools 4.3.1


/**
 * Particoes generated by hbm2java
 */
public class Particao {


     private int id;
     private Maquina maquina;
     private String nomeHd;
     private String formato;
     private String letra;
     private String nomeVolume;
     private String espaco;
     private String espacoLivre;

    public Particao() {
    }

     
     
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Maquina getMaquina() {
        return maquina;
    }

    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }

    public String getNomeHd() {
        return nomeHd;
    }

    public void setNomeHd(String nomeHd) {
        this.nomeHd = nomeHd;
    }

    public String getFormato() {
        return formato;
    }

    public void setFormato(String formato) {
        this.formato = formato;
    }

    public String getLetra() {
        return letra;
    }

    public void setLetra(String letra) {
        this.letra = letra;
    }

    public String getNomeVolume() {
        return nomeVolume;
    }

    public void setNomeVolume(String nomeVolume) {
        this.nomeVolume = nomeVolume;
    }

    public String getEspaco() {
        return espaco;
    }

    public void setEspaco(String espaco) {
        this.espaco = espaco;
    }

    public String getEspacoLivre() {
        return espacoLivre;
    }

    public void setEspacoLivre(String espacoLivre) {
        this.espacoLivre = espacoLivre;
    }

     
     
    }


