package modelo;
// Generated 17/09/2015 16:32:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Software generated by hbm2java
 */
@Entity
@Table(name="software"
    ,schema="public"
)
public class Software  implements java.io.Serializable {


     private int id;
     private Dependencia dependencia;
     private Usuario usuario;
     private String nome;
     private String versao;
     private String desenvolvedor;
     private String comandoDesinstalacao;
     private String siteDesenvolvedor;
     private String siteSoftware;
     private Boolean criadoManualmente;
     private String diretorioInstalacao;
     private Set<SoftwaresMaquina> softwaresMaquinas = new HashSet<SoftwaresMaquina>(0);
     private Set<InstalacaoSoftware> instalacaoSoftwares = new HashSet<InstalacaoSoftware>(0);

    public Software() {
    }

	
    public Software(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Software(int id, Dependencia dependencia, Usuario usuario, String nome, String versao, String desenvolvedor, String comandoDesinstalacao, String siteDesenvolvedor, String siteSoftware, Boolean criadoManualmente, String diretorioInstalacao, Set<SoftwaresMaquina> softwaresMaquinas, Set<InstalacaoSoftware> instalacaoSoftwares) {
       this.id = id;
       this.dependencia = dependencia;
       this.usuario = usuario;
       this.nome = nome;
       this.versao = versao;
       this.desenvolvedor = desenvolvedor;
       this.comandoDesinstalacao = comandoDesinstalacao;
       this.siteDesenvolvedor = siteDesenvolvedor;
       this.siteSoftware = siteSoftware;
       this.criadoManualmente = criadoManualmente;
       this.diretorioInstalacao = diretorioInstalacao;
       this.softwaresMaquinas = softwaresMaquinas;
       this.instalacaoSoftwares = instalacaoSoftwares;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_dependencia")
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nome", nullable=false, length=200)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="versao", length=100)
    public String getVersao() {
        return this.versao;
    }
    
    public void setVersao(String versao) {
        this.versao = versao;
    }

    
    @Column(name="desenvolvedor", length=45)
    public String getDesenvolvedor() {
        return this.desenvolvedor;
    }
    
    public void setDesenvolvedor(String desenvolvedor) {
        this.desenvolvedor = desenvolvedor;
    }

    
    @Column(name="comando_desinstalacao", length=45)
    public String getComandoDesinstalacao() {
        return this.comandoDesinstalacao;
    }
    
    public void setComandoDesinstalacao(String comandoDesinstalacao) {
        this.comandoDesinstalacao = comandoDesinstalacao;
    }

    
    @Column(name="site_desenvolvedor", length=45)
    public String getSiteDesenvolvedor() {
        return this.siteDesenvolvedor;
    }
    
    public void setSiteDesenvolvedor(String siteDesenvolvedor) {
        this.siteDesenvolvedor = siteDesenvolvedor;
    }

    
    @Column(name="site_software", length=45)
    public String getSiteSoftware() {
        return this.siteSoftware;
    }
    
    public void setSiteSoftware(String siteSoftware) {
        this.siteSoftware = siteSoftware;
    }

    
    @Column(name="criado_manualmente")
    public Boolean getCriadoManualmente() {
        return this.criadoManualmente;
    }
    
    public void setCriadoManualmente(Boolean criadoManualmente) {
        this.criadoManualmente = criadoManualmente;
    }

    
    @Column(name="diretorio_instalacao", length=200)
    public String getDiretorioInstalacao() {
        return this.diretorioInstalacao;
    }
    
    public void setDiretorioInstalacao(String diretorioInstalacao) {
        this.diretorioInstalacao = diretorioInstalacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="software")
    public Set<SoftwaresMaquina> getSoftwaresMaquinas() {
        return this.softwaresMaquinas;
    }
    
    public void setSoftwaresMaquinas(Set<SoftwaresMaquina> softwaresMaquinas) {
        this.softwaresMaquinas = softwaresMaquinas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="software")
    public Set<InstalacaoSoftware> getInstalacaoSoftwares() {
        return this.instalacaoSoftwares;
    }
    
    public void setInstalacaoSoftwares(Set<InstalacaoSoftware> instalacaoSoftwares) {
        this.instalacaoSoftwares = instalacaoSoftwares;
    }




}


