package modelo;
// Generated 17/09/2015 16:32:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SoftwaresMaquina generated by hbm2java
 */
@Entity
@Table(name="softwares_maquina"
    ,schema="public"
)
public class SoftwaresMaquina  implements java.io.Serializable {


     private SoftwaresMaquinaId id;
     private Maquina maquina;
     private Software software;
     private Date dtInstalacao;
     private Date dtDeteccao;
     private Date dtUltimaDeteccao;
     private boolean instalado;

    public SoftwaresMaquina() {
    }

	
    public SoftwaresMaquina(SoftwaresMaquinaId id, Maquina maquina, Software software, boolean instalado) {
        this.id = id;
        this.maquina = maquina;
        this.software = software;
        this.instalado = instalado;
    }
    public SoftwaresMaquina(SoftwaresMaquinaId id, Maquina maquina, Software software, Date dtInstalacao, Date dtDeteccao, Date dtUltimaDeteccao, boolean instalado) {
       this.id = id;
       this.maquina = maquina;
       this.software = software;
       this.dtInstalacao = dtInstalacao;
       this.dtDeteccao = dtDeteccao;
       this.dtUltimaDeteccao = dtUltimaDeteccao;
       this.instalado = instalado;
    }
   
     @EmbeddedId
     

    
    @AttributeOverrides( {
        @AttributeOverride(name="idSoftware", column=@Column(name="id_software", nullable=false) ), 
        @AttributeOverride(name="idMaquina", column=@Column(name="id_maquina", nullable=false) ) } )
    public SoftwaresMaquinaId getId() {
        return this.id;
    }
    
    public void setId(SoftwaresMaquinaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_maquina", nullable=false, insertable=false, updatable=false)
    public Maquina getMaquina() {
        return this.maquina;
    }
    
    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_software", nullable=false, insertable=false, updatable=false)
    public Software getSoftware() {
        return this.software;
    }
    
    public void setSoftware(Software software) {
        this.software = software;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_instalacao", length=29)
    public Date getDtInstalacao() {
        return this.dtInstalacao;
    }
    
    public void setDtInstalacao(Date dtInstalacao) {
        this.dtInstalacao = dtInstalacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_deteccao", length=29)
    public Date getDtDeteccao() {
        return this.dtDeteccao;
    }
    
    public void setDtDeteccao(Date dtDeteccao) {
        this.dtDeteccao = dtDeteccao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_ultima_deteccao", length=29)
    public Date getDtUltimaDeteccao() {
        return this.dtUltimaDeteccao;
    }
    
    public void setDtUltimaDeteccao(Date dtUltimaDeteccao) {
        this.dtUltimaDeteccao = dtUltimaDeteccao;
    }

    
    @Column(name="instalado", nullable=false)
    public boolean isInstalado() {
        return this.instalado;
    }
    
    public void setInstalado(boolean instalado) {
        this.instalado = instalado;
    }




}


