package modelo;
// Generated 31/08/2015 19:49:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name="auditoria"
    ,schema="public"
)
public class Auditoria  implements java.io.Serializable {


     private int id;
     private String tabela;
     private Integer idUsuario;
     private Boolean alteradoSistema;
     private char operacao;
     private String alteracoes;
     private Date dt;
     private int idConteudo;

    public Auditoria() {
    }

	
    public Auditoria(int id, String tabela, char operacao, int idConteudo) {
        this.id = id;
        this.tabela = tabela;
        this.operacao = operacao;
        this.idConteudo = idConteudo;
    }
    public Auditoria(int id, String tabela, Integer idUsuario, Boolean alteradoSistema, char operacao, String alteracoes, Date dt, int idConteudo) {
       this.id = id;
       this.tabela = tabela;
       this.idUsuario = idUsuario;
       this.alteradoSistema = alteradoSistema;
       this.operacao = operacao;
       this.alteracoes = alteracoes;
       this.dt = dt;
       this.idConteudo = idConteudo;
    }
   
    @Id     
    @Column(name="id", unique=true, nullable=false)      
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="tabela", nullable=false, length=45)
    public String getTabela() {
        return this.tabela;
    }
    
    public void setTabela(String tabela) {
        this.tabela = tabela;
    }

    
    @Column(name="id_usuario")
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="alterado_sistema")
    public Boolean getAlteradoSistema() {
        return this.alteradoSistema;
    }
    
    public void setAlteradoSistema(Boolean alteradoSistema) {
        this.alteradoSistema = alteradoSistema;
    }

    
    @Column(name="operacao", nullable=false, length=1)
    public char getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(char operacao) {
        this.operacao = operacao;
    }

    
    @Column(name="alteracoes")
    public String getAlteracoes() {
        return this.alteracoes;
    }
    
    public void setAlteracoes(String alteracoes) {
        this.alteracoes = alteracoes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt", length=29)
    public Date getDt() {
        return this.dt;
    }
    
    public void setDt(Date dt) {
        this.dt = dt;
    }

    
    @Column(name="id_conteudo", nullable=false)
    public int getIdConteudo() {
        return this.idConteudo;
    }
    
    public void setIdConteudo(int idConteudo) {
        this.idConteudo = idConteudo;
    }




}


