package modelo;
// Generated 31/08/2015 19:49:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExecucaoInstalacao generated by hbm2java
 */
@Entity
@Table(name="execucao_instalacao"
    ,schema="public"
)
public class ExecucaoInstalacao  implements java.io.Serializable {


     private int id;
     private InstalacaoSoftware instalacaoSoftware;
     private Usuario usuario;
     private Date dt;
     private Set maquinasExecucaoInstalacaos = new HashSet(0);

    public ExecucaoInstalacao() {
    }

	
    public ExecucaoInstalacao(int id) {
        this.id = id;
    }
    public ExecucaoInstalacao(int id, InstalacaoSoftware instalacaoSoftware, Usuario usuario, Date dt, Set maquinasExecucaoInstalacaos) {
       this.id = id;
       this.instalacaoSoftware = instalacaoSoftware;
       this.usuario = usuario;
       this.dt = dt;
       this.maquinasExecucaoInstalacaos = maquinasExecucaoInstalacaos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_instalacao_software")
    public InstalacaoSoftware getInstalacaoSoftware() {
        return this.instalacaoSoftware;
    }
    
    public void setInstalacaoSoftware(InstalacaoSoftware instalacaoSoftware) {
        this.instalacaoSoftware = instalacaoSoftware;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt", length=29)
    public Date getDt() {
        return this.dt;
    }
    
    public void setDt(Date dt) {
        this.dt = dt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="execucaoInstalacao")
    public Set getMaquinasExecucaoInstalacaos() {
        return this.maquinasExecucaoInstalacaos;
    }
    
    public void setMaquinasExecucaoInstalacaos(Set maquinasExecucaoInstalacaos) {
        this.maquinasExecucaoInstalacaos = maquinasExecucaoInstalacaos;
    }




}


