package modelo;
// Generated 17/09/2015 16:32:25 by Hibernate Tools 4.3.1


import controle.IModelo;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name="grupo"
    ,schema="public"
)
public class Grupo  implements java.io.Serializable, IModelo {


     private int id;
     private String nome;
     private String descricao;
     private boolean ativo;
     private Set<Permissao> permissaos = new HashSet<Permissao>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Grupo() {
    }

	
    public Grupo(int id, String nome, String descricao, boolean ativo) {
        this.id = id;
        this.nome = nome;
        this.descricao = descricao;
        this.ativo = ativo;
    }
    public Grupo(int id, String nome, String descricao, boolean ativo, Set<Permissao> permissaos, Set<Usuario> usuarios) {
       this.id = id;
       this.nome = nome;
       this.descricao = descricao;
       this.ativo = ativo;
       this.permissaos = permissaos;
       this.usuarios = usuarios;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao", nullable=false, length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<Permissao> getPermissaos() {
        return this.permissaos;
    }
    
    public void setPermissaos(Set<Permissao> permissaos) {
        this.permissaos = permissaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


