package modelo;
// Generated 31/08/2015 19:49:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstalacaoSoftware generated by hbm2java
 */
@Entity
@Table(name="instalacao_software"
    ,schema="public"
)
public class InstalacaoSoftware  implements java.io.Serializable {


     private int id;
     private Software software;
     private Usuario usuario;
     private String nome;
     private String parametro;
     private Date dtCriacao;
     private boolean ativo;
     private Set execucaoInstalacaos = new HashSet(0);

    public InstalacaoSoftware() {
    }

	
    public InstalacaoSoftware(int id, Software software, Usuario usuario, String nome, String parametro, Date dtCriacao, boolean ativo) {
        this.id = id;
        this.software = software;
        this.usuario = usuario;
        this.nome = nome;
        this.parametro = parametro;
        this.dtCriacao = dtCriacao;
        this.ativo = ativo;
    }
    public InstalacaoSoftware(int id, Software software, Usuario usuario, String nome, String parametro, Date dtCriacao, boolean ativo, Set execucaoInstalacaos) {
       this.id = id;
       this.software = software;
       this.usuario = usuario;
       this.nome = nome;
       this.parametro = parametro;
       this.dtCriacao = dtCriacao;
       this.ativo = ativo;
       this.execucaoInstalacaos = execucaoInstalacaos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_software", nullable=false)
    public Software getSoftware() {
        return this.software;
    }
    
    public void setSoftware(Software software) {
        this.software = software;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="parametro", nullable=false, length=45)
    public String getParametro() {
        return this.parametro;
    }
    
    public void setParametro(String parametro) {
        this.parametro = parametro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_criacao", nullable=false, length=29)
    public Date getDtCriacao() {
        return this.dtCriacao;
    }
    
    public void setDtCriacao(Date dtCriacao) {
        this.dtCriacao = dtCriacao;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="instalacaoSoftware")
    public Set getExecucaoInstalacaos() {
        return this.execucaoInstalacaos;
    }
    
    public void setExecucaoInstalacaos(Set execucaoInstalacaos) {
        this.execucaoInstalacaos = execucaoInstalacaos;
    }




}


