package modelo;
// Generated 17/10/2015 22:43:46 by Hibernate Tools 4.3.1

import controle.IModelo;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Maquina generated by hbm2java
 */
@Entity
@Table(name = "maquina", schema = "public"
)
public class Maquina implements java.io.Serializable, IModelo {

    private int id;
    private Sala sala;
    private Usuario usuario;
    private String host;
    private String dominio;
    private String so;
    private String arquiteturaSo;
    private String versaoSo;
    private String spSo;
    private String fabricanteSo;
    private String rootSo;
    private String memoriaTotal;
    private String fabricantePc;
    private String modeloPc;
    private String cpu;
    private String nucleosCpu;
    private String fabricanteCpu;
    private String bios;
    private String usuarioConectado;
    private Date dtPrimeiraDeteccao;
    private Date dtUltimaDeteccao;
    private Boolean ligado;
    private String observacao;
    private Boolean ativo;
    private String versaoAgente;
    private Set<SoftwaresMaquina> softwaresMaquinas = new HashSet<SoftwaresMaquina>(0);
    private Set<MaquinasExecucaoInstalacao> maquinasExecucaoInstalacaos = new HashSet<MaquinasExecucaoInstalacao>(0);
    private Set<MaquinasExecutarScript> maquinasExecutarScripts = new HashSet<MaquinasExecutarScript>(0);
    private Set<PlacaRede> placaRedes = new HashSet<PlacaRede>(0);
    private Set<Particao> particaos = new HashSet<Particao>(0);

    public Maquina() {
    }

    public Maquina(int id, String host) {
        this.id = id;
        this.host = host;
    }

    public Maquina(int id, Sala sala, Usuario usuario, String host, String dominio, String so, String arquiteturaSo, String versaoSo, String spSo, String fabricanteSo, String rootSo, String memoriaTotal, String fabricantePc, String modeloPc, String cpu, String nucleosCpu, String fabricanteCpu, String bios, String usuarioConectado, Date dtPrimeiraDeteccao, Date dtUltimaDeteccao, Boolean ligado, String observacao, Boolean ativo, String versaoAgente, Set<SoftwaresMaquina> softwaresMaquinas, Set<MaquinasExecucaoInstalacao> maquinasExecucaoInstalacaos, Set<MaquinasExecutarScript> maquinasExecutarScripts, Set<PlacaRede> placaRedes, Set<Particao> particaos) {
        this.id = id;
        this.sala = sala;
        this.usuario = usuario;
        this.host = host;
        this.dominio = dominio;
        this.so = so;
        this.arquiteturaSo = arquiteturaSo;
        this.versaoSo = versaoSo;
        this.spSo = spSo;
        this.fabricanteSo = fabricanteSo;
        this.rootSo = rootSo;
        this.memoriaTotal = memoriaTotal;
        this.fabricantePc = fabricantePc;
        this.modeloPc = modeloPc;
        this.cpu = cpu;
        this.nucleosCpu = nucleosCpu;
        this.fabricanteCpu = fabricanteCpu;
        this.bios = bios;
        this.usuarioConectado = usuarioConectado;
        this.dtPrimeiraDeteccao = dtPrimeiraDeteccao;
        this.dtUltimaDeteccao = dtUltimaDeteccao;
        this.ligado = ligado;
        this.observacao = observacao;
        this.ativo = ativo;
        this.versaoAgente = versaoAgente;
        this.softwaresMaquinas = softwaresMaquinas;
        this.maquinasExecucaoInstalacaos = maquinasExecucaoInstalacaos;
        this.maquinasExecutarScripts = maquinasExecutarScripts;
        this.placaRedes = placaRedes;
        this.particaos = particaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    @Override
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_sala")
    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario_modificador")
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "host", nullable = false, length = 20)
    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    @Column(name = "dominio", length = 20)
    public String getDominio() {
        return this.dominio;
    }

    public void setDominio(String dominio) {
        this.dominio = dominio;
    }

    @Column(name = "so", length = 100)
    public String getSo() {
        return this.so;
    }

    public void setSo(String so) {
        this.so = so;
    }

    @Column(name = "arquitetura_so", length = 10)
    public String getArquiteturaSo() {
        return this.arquiteturaSo;
    }

    public void setArquiteturaSo(String arquiteturaSo) {
        this.arquiteturaSo = arquiteturaSo;
    }

    @Column(name = "versao_so", length = 50)
    public String getVersaoSo() {
        return this.versaoSo;
    }

    public void setVersaoSo(String versaoSo) {
        this.versaoSo = versaoSo;
    }

    @Column(name = "sp_so", length = 100)
    public String getSpSo() {
        return this.spSo;
    }

    public void setSpSo(String spSo) {
        this.spSo = spSo;
    }

    @Column(name = "fabricante_so", length = 50)
    public String getFabricanteSo() {
        return this.fabricanteSo;
    }

    public void setFabricanteSo(String fabricanteSo) {
        this.fabricanteSo = fabricanteSo;
    }

    @Column(name = "root_so", length = 100)
    public String getRootSo() {
        return this.rootSo;
    }

    public void setRootSo(String rootSo) {
        this.rootSo = rootSo;
    }

    @Column(name = "memoria_total", length = 100)
    public String getMemoriaTotal() {
        return this.memoriaTotal;
    }

    public void setMemoriaTotal(String memoriaTotal) {
        this.memoriaTotal = memoriaTotal;
    }

    @Column(name = "fabricante_pc", length = 100)
    public String getFabricantePc() {
        return this.fabricantePc;
    }

    public void setFabricantePc(String fabricantePc) {
        this.fabricantePc = fabricantePc;
    }

    @Column(name = "modelo_pc", length = 100)
    public String getModeloPc() {
        return this.modeloPc;
    }

    public void setModeloPc(String modeloPc) {
        this.modeloPc = modeloPc;
    }

    @Column(name = "cpu", length = 200)
    public String getCpu() {
        return this.cpu;
    }

    public void setCpu(String cpu) {
        this.cpu = cpu;
    }

    @Column(name = "nucleos_cpu", length = 50)
    public String getNucleosCpu() {
        return this.nucleosCpu;
    }

    public void setNucleosCpu(String nucleosCpu) {
        this.nucleosCpu = nucleosCpu;
    }

    @Column(name = "fabricante_cpu", length = 50)
    public String getFabricanteCpu() {
        return this.fabricanteCpu;
    }

    public void setFabricanteCpu(String fabricanteCpu) {
        this.fabricanteCpu = fabricanteCpu;
    }

    @Column(name = "bios", length = 100)
    public String getBios() {
        return this.bios;
    }

    public void setBios(String bios) {
        this.bios = bios;
    }

    @Column(name = "usuario_conectado", length = 50)
    public String getUsuarioConectado() {
        return this.usuarioConectado;
    }

    public void setUsuarioConectado(String usuarioConectado) {
        this.usuarioConectado = usuarioConectado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_primeira_deteccao", length = 29)
    public Date getDtPrimeiraDeteccao() {
        return this.dtPrimeiraDeteccao;
    }

    public void setDtPrimeiraDeteccao(Date dtPrimeiraDeteccao) {
        this.dtPrimeiraDeteccao = dtPrimeiraDeteccao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_ultima_deteccao", length = 29)
    public Date getDtUltimaDeteccao() {
        return this.dtUltimaDeteccao;
    }

    public void setDtUltimaDeteccao(Date dtUltimaDeteccao) {
        this.dtUltimaDeteccao = dtUltimaDeteccao;
    }

    @Column(name = "ligado")
    public Boolean getLigado() {
        return this.ligado;
    }

    public void setLigado(Boolean ligado) {
        this.ligado = ligado;
    }

    @Column(name = "observacao")
    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    @Column(name = "ativo")
    public Boolean getAtivo() {
        return this.ativo;
    }

    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

    @Column(name = "versao_agente", length = 15)
    public String getVersaoAgente() {
        return this.versaoAgente;
    }

    public void setVersaoAgente(String versaoAgente) {
        this.versaoAgente = versaoAgente;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
    public Set<SoftwaresMaquina> getSoftwaresMaquinas() {
        return this.softwaresMaquinas;
    }

    public void setSoftwaresMaquinas(Set<SoftwaresMaquina> softwaresMaquinas) {
        this.softwaresMaquinas = softwaresMaquinas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
    public Set<MaquinasExecucaoInstalacao> getMaquinasExecucaoInstalacaos() {
        return this.maquinasExecucaoInstalacaos;
    }

    public void setMaquinasExecucaoInstalacaos(Set<MaquinasExecucaoInstalacao> maquinasExecucaoInstalacaos) {
        this.maquinasExecucaoInstalacaos = maquinasExecucaoInstalacaos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
    public Set<MaquinasExecutarScript> getMaquinasExecutarScripts() {
        return this.maquinasExecutarScripts;
    }

    public void setMaquinasExecutarScripts(Set<MaquinasExecutarScript> maquinasExecutarScripts) {
        this.maquinasExecutarScripts = maquinasExecutarScripts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
    public Set<PlacaRede> getPlacaRedes() {
        return this.placaRedes;
    }

    public void setPlacaRedes(Set<PlacaRede> placaRedes) {
        this.placaRedes = placaRedes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
    public Set<Particao> getParticaos() {
        return this.particaos;
    }

    public void setParticaos(Set<Particao> particaos) {
        this.particaos = particaos;
    }

    @Override
    @Transient
    public String getNome() {
        return this.host;
    }

    @Override
    public void setNome(String nome) {
        this.host = nome;
    }

}
