package modelo;
// Generated 17/09/2015 16:32:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaquinasExecucaoInstalacaoId generated by hbm2java
 */
@Embeddable
public class MaquinasExecucaoInstalacaoId  implements java.io.Serializable {


     private int idMaquina;
     private int idExecucaoInstalacao;

    public MaquinasExecucaoInstalacaoId() {
    }

    public MaquinasExecucaoInstalacaoId(int idMaquina, int idExecucaoInstalacao) {
       this.idMaquina = idMaquina;
       this.idExecucaoInstalacao = idExecucaoInstalacao;
    }
   


    @Column(name="id_maquina", nullable=false)
    public int getIdMaquina() {
        return this.idMaquina;
    }
    
    public void setIdMaquina(int idMaquina) {
        this.idMaquina = idMaquina;
    }


    @Column(name="id_execucao_instalacao", nullable=false)
    public int getIdExecucaoInstalacao() {
        return this.idExecucaoInstalacao;
    }
    
    public void setIdExecucaoInstalacao(int idExecucaoInstalacao) {
        this.idExecucaoInstalacao = idExecucaoInstalacao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MaquinasExecucaoInstalacaoId) ) return false;
		 MaquinasExecucaoInstalacaoId castOther = ( MaquinasExecucaoInstalacaoId ) other; 
         
		 return (this.getIdMaquina()==castOther.getIdMaquina())
 && (this.getIdExecucaoInstalacao()==castOther.getIdExecucaoInstalacao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMaquina();
         result = 37 * result + this.getIdExecucaoInstalacao();
         return result;
   }   


}


