package modelo;
// Generated 14/09/2015 13:16:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "permissao", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"id_grupo", "id_tela"}),
    @UniqueConstraint(columnNames = {"id_usuario", "id_tela"})}
)
public class Permissao implements java.io.Serializable {

    private int id;
    private Grupo grupo;
    private Usuario usuario;
    private int idTela;
    private boolean inserir;
    private boolean editar;
    private boolean inativar;
    private Boolean ler;

    public Permissao() {
    }

    public Permissao(int id, int idTela, boolean inserir, boolean editar, boolean inativar) {
        this.id = id;
        this.idTela = idTela;
        this.inserir = inserir;
        this.editar = editar;
        this.inativar = inativar;
    }

    public Permissao(int id, Grupo grupo, Usuario usuario, int idTela, boolean inserir, boolean editar, boolean inativar, Boolean ler) {
        this.id = id;
        this.grupo = grupo;
        this.usuario = usuario;
        this.idTela = idTela;
        this.inserir = inserir;
        this.editar = editar;
        this.inativar = inativar;
        this.ler = ler;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_grupo")
    public Grupo getGrupo() {
        return this.grupo;
    }

    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "id_tela", nullable = false)
    public int getIdTela() {
        return this.idTela;
    }

    public void setIdTela(int idTela) {
        this.idTela = idTela;
    }

    @Column(name = "inserir", nullable = false)
    public boolean isInserir() {
        return this.inserir;
    }

    public void setInserir(boolean inserir) {
        this.inserir = inserir;
    }

    @Column(name = "editar", nullable = false)
    public boolean isEditar() {
        return this.editar;
    }

    public void setEditar(boolean editar) {
        this.editar = editar;
    }

    @Column(name = "inativar", nullable = false)
    public boolean isInativar() {
        return this.inativar;
    }

    public void setInativar(boolean inativar) {
        this.inativar = inativar;
    }

    @Column(name = "ler")
    public Boolean getLer() {
        return this.ler;
    }

    public void setLer(Boolean ler) {
        this.ler = ler;
    }

}
