package modelo;
// Generated 31/08/2015 19:49:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlacaRede generated by hbm2java
 */
@Entity
@Table(name="placa_rede"
    ,schema="public"
)
public class PlacaRede  implements java.io.Serializable {


     private int id;
     private Maquina maquina;
     private String nome;
     private String ipv4;
     private String ipv6;
     private String mac;
     private Boolean principal;

    public PlacaRede() {
    }

	
    public PlacaRede(int id, Maquina maquina) {
        this.id = id;
        this.maquina = maquina;
    }
    public PlacaRede(int id, Maquina maquina, String nome, String ipv4, String ipv6, String mac, Boolean principal) {
       this.id = id;
       this.maquina = maquina;
       this.nome = nome;
       this.ipv4 = ipv4;
       this.ipv6 = ipv6;
       this.mac = mac;
       this.principal = principal;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_maquina", nullable=false)
    public Maquina getMaquina() {
        return this.maquina;
    }
    
    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }

    
    @Column(name="nome", length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="ipv4", length=15)
    public String getIpv4() {
        return this.ipv4;
    }
    
    public void setIpv4(String ipv4) {
        this.ipv4 = ipv4;
    }

    
    @Column(name="ipv6", length=39)
    public String getIpv6() {
        return this.ipv6;
    }
    
    public void setIpv6(String ipv6) {
        this.ipv6 = ipv6;
    }

    
    @Column(name="mac", length=17)
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }

    
    @Column(name="principal")
    public Boolean getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(Boolean principal) {
        this.principal = principal;
    }




}


