package modelo;
// Generated 17/10/2015 22:43:46 by Hibernate Tools 4.3.1

import controle.IModelo;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * SoftwaresMaquina generated by hbm2java
 */
@Entity
@Table(name = "softwares_maquina", schema = "public"
)
public class SoftwaresMaquina implements java.io.Serializable, IModelo {

    private int id;
    private Maquina maquina;
    private Software software;
    private Date dtInstalacao;
    private Date dtDeteccao;
    private Date dtUltimaDeteccao;
    private boolean instalado;

    public SoftwaresMaquina() {
    }

    public SoftwaresMaquina(int id, Maquina maquina, Software software, boolean instalado) {
        this.id = id;
        this.maquina = maquina;
        this.software = software;
        this.instalado = instalado;
    }

    public SoftwaresMaquina(int id, Maquina maquina, Software software, Date dtInstalacao, Date dtDeteccao, Date dtUltimaDeteccao, boolean instalado) {
        this.id = id;
        this.maquina = maquina;
        this.software = software;
        this.dtInstalacao = dtInstalacao;
        this.dtDeteccao = dtDeteccao;
        this.dtUltimaDeteccao = dtUltimaDeteccao;
        this.instalado = instalado;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    @Override
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_maquina", nullable = false)
    public Maquina getMaquina() {
        return this.maquina;
    }

    public void setMaquina(Maquina maquina) {
        this.maquina = maquina;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_software", nullable = false)
    public Software getSoftware() {
        return this.software;
    }

    public void setSoftware(Software software) {
        this.software = software;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_instalacao", length = 29)
    public Date getDtInstalacao() {
        return this.dtInstalacao;
    }

    public void setDtInstalacao(Date dtInstalacao) {
        this.dtInstalacao = dtInstalacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_deteccao", length = 29)
    public Date getDtDeteccao() {
        return this.dtDeteccao;
    }

    public void setDtDeteccao(Date dtDeteccao) {
        this.dtDeteccao = dtDeteccao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dt_ultima_deteccao", length = 29)
    public Date getDtUltimaDeteccao() {
        return this.dtUltimaDeteccao;
    }

    public void setDtUltimaDeteccao(Date dtUltimaDeteccao) {
        this.dtUltimaDeteccao = dtUltimaDeteccao;
    }

    @Column(name = "instalado", nullable = false)
    public boolean isInstalado() {
        return this.instalado;
    }

    public void setInstalado(boolean instalado) {
        this.instalado = instalado;
    }

    @Override
    @Transient
    public String getNome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setNome(String nome) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
