package modelo;
// Generated 17/09/2015 16:32:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SoftwaresMaquinaId generated by hbm2java
 */
@Embeddable
public class SoftwaresMaquinaId  implements java.io.Serializable {


     private int idSoftware;
     private int idMaquina;

    public SoftwaresMaquinaId() {
    }

    public SoftwaresMaquinaId(int idSoftware, int idMaquina) {
       this.idSoftware = idSoftware;
       this.idMaquina = idMaquina;
    }
   


    @Column(name="id_software", nullable=false)
    public int getIdSoftware() {
        return this.idSoftware;
    }
    
    public void setIdSoftware(int idSoftware) {
        this.idSoftware = idSoftware;
    }


    @Column(name="id_maquina", nullable=false)
    public int getIdMaquina() {
        return this.idMaquina;
    }
    
    public void setIdMaquina(int idMaquina) {
        this.idMaquina = idMaquina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SoftwaresMaquinaId) ) return false;
		 SoftwaresMaquinaId castOther = ( SoftwaresMaquinaId ) other; 
         
		 return (this.getIdSoftware()==castOther.getIdSoftware())
 && (this.getIdMaquina()==castOther.getIdMaquina());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSoftware();
         result = 37 * result + this.getIdMaquina();
         return result;
   }   


}


