/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleUsuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import modelo.Usuario;

/**
 *
 * @author eduar_000
 */
public class JfMain extends javax.swing.JFrame {

    protected Usuario usuario;
    protected ControleUsuario controleUsuario;

    public JfMain() {
        initComponents();
    }

    public JfMain(Usuario usuario) {
        this.usuario = usuario;
        controleUsuario = new ControleUsuario();
        initComponents();
        aplicaIcones();
        this.setLocation(0, 0);

        this.setTitle("QIT - User: " + usuario.getLogin());

    }

    private void aplicaIcones() {

        btMaquinas.setIcon(new ImageIcon("src/visao/img/ico_pc.png"));
        btMaquinas.setToolTipText("Máquinas");
        btSoftwares.setIcon(new ImageIcon("src/visao/img/ico_sw.png"));
        btSoftwares.setToolTipText("Softwares");
        btScripts.setIcon(new ImageIcon("src/visao/img/ico_cmd.png"));
        btScripts.setToolTipText("Scripts");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        btMaquinas = new javax.swing.JButton();
        btSoftwares = new javax.swing.JButton();
        btScripts = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmUsuario = new javax.swing.JMenu();
        jimUsuario = new javax.swing.JMenuItem();
        jimGrupoUsuario = new javax.swing.JMenuItem();
        jimPermissao = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jmInventario = new javax.swing.JMenu();
        jimMaquinas = new javax.swing.JMenuItem();
        jimMasquinasSoftwares = new javax.swing.JMenuItem();
        jimPredio = new javax.swing.JMenuItem();
        jimSala = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jmExecucaoScript = new javax.swing.JMenuItem();
        jmResultadosExecucaoScript = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaquinasActionPerformed(evt);
            }
        });

        btSoftwares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSoftwaresActionPerformed(evt);
            }
        });

        btScripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btScriptsActionPerformed(evt);
            }
        });

        jmUsuario.setText("Usuarios");

        jimUsuario.setText("Usuarios");
        jimUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimUsuarioActionPerformed(evt);
            }
        });
        jmUsuario.add(jimUsuario);

        jimGrupoUsuario.setText("Grupos de Usuários");
        jimGrupoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimGrupoUsuarioActionPerformed(evt);
            }
        });
        jmUsuario.add(jimGrupoUsuario);

        jimPermissao.setText("Permissão");
        jimPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimPermissaoActionPerformed(evt);
            }
        });
        jmUsuario.add(jimPermissao);

        jMenuItem5.setText("Alterar senha");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmUsuario.add(jMenuItem5);

        jMenuBar1.add(jmUsuario);

        jmInventario.setText("Inventário");

        jimMaquinas.setText("Maquinas");
        jimMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimMaquinasActionPerformed(evt);
            }
        });
        jmInventario.add(jimMaquinas);

        jimMasquinasSoftwares.setText("Softwares");
        jimMasquinasSoftwares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimMasquinasSoftwaresActionPerformed(evt);
            }
        });
        jmInventario.add(jimMasquinasSoftwares);

        jimPredio.setText("Prédio");
        jimPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimPredioActionPerformed(evt);
            }
        });
        jmInventario.add(jimPredio);

        jimSala.setText("Sala");
        jimSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimSalaActionPerformed(evt);
            }
        });
        jmInventario.add(jimSala);

        jMenuBar1.add(jmInventario);

        jMenu1.setText("Relatorios");

        jMenu3.setText("Usuarios");

        jMenuItem1.setText("Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Grupos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Permissões");
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenu4.setText("Inventario");

        jMenuItem8.setText("Software");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuração");

        jMenuItem4.setText("Sistema");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Script");

        jMenuItem7.setText("Scripts");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jmExecucaoScript.setText("Execução de Script");
        jmExecucaoScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExecucaoScriptActionPerformed(evt);
            }
        });
        jMenu5.add(jmExecucaoScript);

        jmResultadosExecucaoScript.setText("Resultados Execução de Script");
        jmResultadosExecucaoScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmResultadosExecucaoScriptActionPerformed(evt);
            }
        });
        jMenu5.add(jmResultadosExecucaoScript);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Auditoria");

        jMenuItem11.setText("Consulta");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSoftwares, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btScripts, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btScripts, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(btSoftwares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jimUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimUsuarioActionPerformed
        new JfUsuario(usuario);        // TODO add your handling code here:
    }//GEN-LAST:event_jimUsuarioActionPerformed

    private void jimGrupoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimGrupoUsuarioActionPerformed
        new JfGrupo(usuario);
    }//GEN-LAST:event_jimGrupoUsuarioActionPerformed

    private void jimPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimPermissaoActionPerformed
        new JfPermissao(usuario);
    }//GEN-LAST:event_jimPermissaoActionPerformed

    private void btMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaquinasActionPerformed
        new JfMaquina(usuario);        // TODO add your handling code here:
    }//GEN-LAST:event_btMaquinasActionPerformed

    private void btSoftwaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSoftwaresActionPerformed
        new JfMasquinasSoftwares(usuario);

    }//GEN-LAST:event_btSoftwaresActionPerformed

    private void btScriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btScriptsActionPerformed
        new JfScript(usuario);
    }//GEN-LAST:event_btScriptsActionPerformed

    private void jimPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimPredioActionPerformed
        new JfPredio(usuario);
    }//GEN-LAST:event_jimPredioActionPerformed

    private void jimSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimSalaActionPerformed
        new JfSala(usuario);
    }//GEN-LAST:event_jimSalaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new JfRelatorioUsuario(usuario);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new JfRelatorioGrupo(usuario);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new JfConfiguracao(usuario);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new JfScript(usuario);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new JfRelatorioSoftware(usuario);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new JfAuditoria(usuario);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jmExecucaoScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExecucaoScriptActionPerformed
        new JfExecutarScript(usuario);
    }//GEN-LAST:event_jmExecucaoScriptActionPerformed

    private void jmResultadosExecucaoScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmResultadosExecucaoScriptActionPerformed
        new JfMaquinasExecutarScript(usuario, 0);
    }//GEN-LAST:event_jmResultadosExecucaoScriptActionPerformed

    private void jimMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimMaquinasActionPerformed
        new JfMaquina(usuario);
    }//GEN-LAST:event_jimMaquinasActionPerformed

    private void jimMasquinasSoftwaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimMasquinasSoftwaresActionPerformed
        new JfMasquinasSoftwares(usuario);        // TODO add your handling code here:
    }//GEN-LAST:event_jimMasquinasSoftwaresActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new JfAlterarSenha(usuario);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMaquinas;
    private javax.swing.JButton btScripts;
    private javax.swing.JButton btSoftwares;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jimGrupoUsuario;
    private javax.swing.JMenuItem jimMaquinas;
    private javax.swing.JMenuItem jimMasquinasSoftwares;
    private javax.swing.JMenuItem jimPermissao;
    private javax.swing.JMenuItem jimPredio;
    private javax.swing.JMenuItem jimSala;
    private javax.swing.JMenuItem jimUsuario;
    private javax.swing.JMenuItem jmExecucaoScript;
    private javax.swing.JMenu jmInventario;
    private javax.swing.JMenuItem jmResultadosExecucaoScript;
    private javax.swing.JMenu jmUsuario;
    // End of variables declaration//GEN-END:variables
}
